version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.bundev
    env_file:
      - .env.local
    ports:
      - 5000:5000
    networks:
      - backend-drizzle
    volumes:
      - ./:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
    command: bun run dev
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:16.2-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-drizzle

  adminer:
    container_name: adminer
    image: adminer:4.8.1
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: db_postgres
    ports:
      - 8085:8080
    networks:
      - backend-drizzle
    depends_on:
      - postgres

  redis:
    container_name: redis
    image: redis:7.2-alpine
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - 6379:6379
    networks:
      - backend-drizzle

networks:
  backend-drizzle:

volumes:
  backend:
  postgres-data:
